//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.296
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWPF.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Connexion", ReplyAction="http://tempuri.org/IService/ConnexionResponse")]
        ObjetDefinition.Utilisateur Connexion(string pseudo, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Inscription", ReplyAction="http://tempuri.org/IService/InscriptionResponse")]
        ObjetDefinition.Utilisateur Inscription(ObjetDefinition.Utilisateur u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlbumCollection", ReplyAction="http://tempuri.org/IService/GetAlbumCollectionResponse")]
        ObjetDefinition.Album[] GetAlbumCollection(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddAlbum", ReplyAction="http://tempuri.org/IService/AddAlbumResponse")]
        ObjetDefinition.Album AddAlbum(ObjetDefinition.Album a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveAlbum", ReplyAction="http://tempuri.org/IService/RemoveAlbumResponse")]
        void RemoveAlbum(int userId, int albumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPicturesFromUserAlbum", ReplyAction="http://tempuri.org/IService/GetPicturesFromUserAlbumResponse")]
        ObjetDefinition.ImageInfo[] GetPicturesFromUserAlbum(int userId, int albumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPicturesIdFromUserAlbum", ReplyAction="http://tempuri.org/IService/GetPicturesIdFromUserAlbumResponse")]
        int[] GetPicturesIdFromUserAlbum(int userId, int albumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPicturesAlbumTuple", ReplyAction="http://tempuri.org/IService/GetPicturesAlbumTupleResponse")]
        System.Tuple<int, string>[] GetPicturesAlbumTuple(int userId, int albumId);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageDownloadRequest) du message ImageDownloadRequest ne correspond pas à la valeur par défaut (GetPicture)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPicture", ReplyAction="http://tempuri.org/IService/GetPictureResponse")]
        ClientWPF.WebService.ImageDownloadResponse GetPicture(ClientWPF.WebService.ImageDownloadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImagethumbnailDownloadRequest) du message ImagethumbnailDownloadRequest ne correspond pas à la valeur par défaut (GetPictureThumbnail)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPictureThumbnail", ReplyAction="http://tempuri.org/IService/GetPictureThumbnailResponse")]
        ClientWPF.WebService.ImageDownloadResponse GetPictureThumbnail(ClientWPF.WebService.ImagethumbnailDownloadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'opération AddPicture n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPicture", ReplyAction="http://tempuri.org/IService/AddPictureResponse")]
        ClientWPF.WebService.AddPictureResponse AddPicture(ClientWPF.WebService.Picture request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemovePicture", ReplyAction="http://tempuri.org/IService/RemovePictureResponse")]
        void RemovePicture(int userId, int albumId, int photoId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ObjetDefinition.ImageInfo ImageInfo;
        
        public ImageDownloadRequest() {
        }
        
        public ImageDownloadRequest(ObjetDefinition.ImageInfo ImageInfo) {
            this.ImageInfo = ImageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageDownloadResponse() {
        }
        
        public ImageDownloadResponse(System.IO.Stream ImageData) {
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImagethumbnailDownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImagethumbnailDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ObjetDefinition.ImageInfo ImageInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int MaxLargestSide;
        
        public ImagethumbnailDownloadRequest() {
        }
        
        public ImagethumbnailDownloadRequest(ObjetDefinition.ImageInfo ImageInfo, int MaxLargestSide) {
            this.ImageInfo = ImageInfo;
            this.MaxLargestSide = MaxLargestSide;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Picture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Picture {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ObjetDefinition.ImageInfo ImageInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public Picture() {
        }
        
        public Picture(ObjetDefinition.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            this.ImageInfo = ImageInfo;
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPictureResponse {
        
        public AddPictureResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientWPF.WebService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClientWPF.WebService.IService>, ClientWPF.WebService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ObjetDefinition.Utilisateur Connexion(string pseudo, string mdp) {
            return base.Channel.Connexion(pseudo, mdp);
        }
        
        public ObjetDefinition.Utilisateur Inscription(ObjetDefinition.Utilisateur u) {
            return base.Channel.Inscription(u);
        }
        
        public ObjetDefinition.Album[] GetAlbumCollection(int userId) {
            return base.Channel.GetAlbumCollection(userId);
        }
        
        public ObjetDefinition.Album AddAlbum(ObjetDefinition.Album a) {
            return base.Channel.AddAlbum(a);
        }
        
        public void RemoveAlbum(int userId, int albumId) {
            base.Channel.RemoveAlbum(userId, albumId);
        }
        
        public ObjetDefinition.ImageInfo[] GetPicturesFromUserAlbum(int userId, int albumId) {
            return base.Channel.GetPicturesFromUserAlbum(userId, albumId);
        }
        
        public int[] GetPicturesIdFromUserAlbum(int userId, int albumId) {
            return base.Channel.GetPicturesIdFromUserAlbum(userId, albumId);
        }
        
        public System.Tuple<int, string>[] GetPicturesAlbumTuple(int userId, int albumId) {
            return base.Channel.GetPicturesAlbumTuple(userId, albumId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPF.WebService.ImageDownloadResponse ClientWPF.WebService.IService.GetPicture(ClientWPF.WebService.ImageDownloadRequest request) {
            return base.Channel.GetPicture(request);
        }
        
        public System.IO.Stream GetPicture(ObjetDefinition.ImageInfo ImageInfo) {
            ClientWPF.WebService.ImageDownloadRequest inValue = new ClientWPF.WebService.ImageDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            ClientWPF.WebService.ImageDownloadResponse retVal = ((ClientWPF.WebService.IService)(this)).GetPicture(inValue);
            return retVal.ImageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPF.WebService.ImageDownloadResponse ClientWPF.WebService.IService.GetPictureThumbnail(ClientWPF.WebService.ImagethumbnailDownloadRequest request) {
            return base.Channel.GetPictureThumbnail(request);
        }
        
        public System.IO.Stream GetPictureThumbnail(ObjetDefinition.ImageInfo ImageInfo, int MaxLargestSide) {
            ClientWPF.WebService.ImagethumbnailDownloadRequest inValue = new ClientWPF.WebService.ImagethumbnailDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            inValue.MaxLargestSide = MaxLargestSide;
            ClientWPF.WebService.ImageDownloadResponse retVal = ((ClientWPF.WebService.IService)(this)).GetPictureThumbnail(inValue);
            return retVal.ImageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWPF.WebService.AddPictureResponse ClientWPF.WebService.IService.AddPicture(ClientWPF.WebService.Picture request) {
            return base.Channel.AddPicture(request);
        }
        
        public void AddPicture(ObjetDefinition.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            ClientWPF.WebService.Picture inValue = new ClientWPF.WebService.Picture();
            inValue.ImageInfo = ImageInfo;
            inValue.ImageData = ImageData;
            ClientWPF.WebService.AddPictureResponse retVal = ((ClientWPF.WebService.IService)(this)).AddPicture(inValue);
        }
        
        public void RemovePicture(int userId, int albumId, int photoId) {
            base.Channel.RemovePicture(userId, albumId, photoId);
        }
    }
}
